# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'WeatherForecast' do
    pod 'RealmSwift'
    pod 'Alamofire', '~> 4.7'
    pod 'ObjectMapper', '~> 3.1'
end
